tasks:
  - name: update package cache
    ansible.builtin.yum:
      name: '*'
      state: latest
    become: true
    
  - name: install epel-release package , yum-utils , git ,pip
    ansible.builtin.yum:
      name:
        - epel-release
        - yum-utils
        - git
        - python-pip
      state: latest
    become: true

  - name: add docker-ce repo
    ansible.builtin.yum_repository:
      name: docker-ce
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: install docker packages
    ansible.builtin.yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose 
      state: latest
      become: true
    
  - name: start docker deamon
    ansible.builtin.service:
      state: started
      name: docker
    become: true
    
