---


- name: build app server
  hosts: hosts
  become: true
  tasks:
    - name: update package cache
      ansible.builtin.yum:
        name: '*'
        state: latest
      
    - name: install yum-utils , git , pip
      ansible.builtin.yum:
        name:
          - yum-utils
          - git
          - python-pip
        state: latest
        
    - name: install docker 
      ansible.builtin.yum:
        name:
          - docker
        state: latest
      
    - name: start docker deamon
      ansible.builtin.service:
        state: started
        name: docker

    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/noahaviv/CICD.git
        dest: /home/ec2-user

    - name: add user to docker group
      ansible.builtin.command: usermod -a -G docker ec2-user

#    - name: build docker image
#     community.docker.docker_image_build:
 #       name: 
